-- Creating USERS table
CREATE TABLE USERS (
   USER_ID INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   USER_CLASS VARCHAR(1),
   USERNAME VARCHAR(50),
   FIRST_NAME VARCHAR(50),
   LAST_NAME VARCHAR(50),
   EMAIL VARCHAR(50),
   PASSWORD INTEGER,
   BALANCE DOUBLE,
   VERIFIED VARCHAR(1)
);

-- Creating ITEMS table
CREATE TABLE ITEMS (
   ITEM_ID INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   ITEM_CLASS VARCHAR(1),
   ITEM_NAME VARCHAR(50),
   ITEM_PRICE DOUBLE,
   HAS_MEAT_OR_ALCOHOL VARCHAR(1),
   INGREDIENTS VARCHAR(255)
);

-- Creating USER_HAS_ITEM table
CREATE TABLE USER_HAS_ITEM (
   USER_ID INT,
   ITEM_ID INT,
   FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
   FOREIGN KEY (ITEM_ID) REFERENCES ITEMS (ITEM_ID),
   CONSTRAINT PK_USER_ITEM PRIMARY KEY (USER_ID, ITEM_ID)
);

-- Populating the tables
--   Adding an admin to USERS
INSERT INTO USERS (USER_CLASS, USERNAME, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD) VALUES ('a', 'lisa', 'lisa', 'simpson', 'lisa@simpson.com', 1509442);
--   Adding a buyer to USERS
INSERT INTO USERS (USER_CLASS, USERNAME, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, BALANCE) VALUES ('b', 'marge', 'marge', 'simpson', 'marge@simpson.com', 1509442, 0.0);
--   Adding a seller to USERS
INSERT INTO USERS (USER_CLASS, USERNAME, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, VERIFIED) VALUES ('s', 'Barty''s', 'bart', 'simpson', 'bart@simpson.com', 1509442, 'f');
--   Adding foods to ITEMS
INSERT INTO ITEMS (ITEM_CLASS, ITEM_NAME, ITEM_PRICE, HAS_MEAT_OR_ALCOHOL, INGREDIENTS) VALUES ('f', 'Pasta', 15.0, 'f', 'spaghetti, pesto sauce, parmigiano');
INSERT INTO ITEMS (ITEM_CLASS, ITEM_NAME, ITEM_PRICE, HAS_MEAT_OR_ALCOHOL, INGREDIENTS) VALUES ('f', 'Pizza', 12.0, 'f', 'dough, tomato sauce, mozarella');
INSERT INTO ITEMS (ITEM_CLASS, ITEM_NAME, ITEM_PRICE, HAS_MEAT_OR_ALCOHOL, INGREDIENTS) VALUES ('f', 'Chicken Curry', 18.0, 't', 'chicken, curry sauce');
--   Adding drinks to ITEMS
INSERT INTO ITEMS (ITEM_CLASS, ITEM_NAME, ITEM_PRICE, HAS_MEAT_OR_ALCOHOL) VALUES ('d', 'Water', 1.0, 'f');
INSERT INTO ITEMS (ITEM_CLASS, ITEM_NAME, ITEM_PRICE, HAS_MEAT_OR_ALCOHOL) VALUES ('d', 'Ice Tea', 2.0, 'f');
INSERT INTO ITEMS (ITEM_CLASS, ITEM_NAME, ITEM_PRICE, HAS_MEAT_OR_ALCOHOL) VALUES ('d', 'Vodka', 5.0, 't');
--   Seller Barty's (ID=3) sells foods
INSERT INTO USER_HAS_ITEM (USER_ID, ITEM_ID) VALUES (3, 1);
INSERT INTO USER_HAS_ITEM (USER_ID, ITEM_ID) VALUES (3, 2);
INSERT INTO USER_HAS_ITEM (USER_ID, ITEM_ID) VALUES (3, 3);
--   Seller Barty's (ID=3) sells drinks
INSERT INTO USER_HAS_ITEM (USER_ID, ITEM_ID) VALUES (3, 4);
INSERT INTO USER_HAS_ITEM (USER_ID, ITEM_ID) VALUES (3, 5);
INSERT INTO USER_HAS_ITEM (USER_ID, ITEM_ID) VALUES (3, 6);
--   Buyer marge (ID=2) has a food in her shopping cart
INSERT INTO USER_HAS_ITEM (USER_ID, ITEM_ID) VALUES (2, 3);
--   Buyer marge (ID=2) has a drink in her shopping cart
INSERT INTO USER_HAS_ITEM (USER_ID, ITEM_ID) VALUES (2, 5);